name: flutter_build_helper
description: A command-line tool which helps you to build and tag artifacts with ease.
version: 0.2.1
repository: https://github.com/tarekbazine/flutter_build_helper

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  args: ^2.4.0
  yaml: ^3.1.1
  path: ^1.8.3

dev_dependencies:
  test: ^1.16.8