name: flutter_build_helper
description: A command-line tool which helps you to build and tag artifacts with ease.
version: 1.3.0+5
author: Tarek BAZINE (@tarekbazine)
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  args: 2.0.0
  yaml: ^3.1.0
  path: ^1.8.0

dev_dependencies:
  test: ^1.16.8